### ISSUE TITLE
[TASK] Upgrade ddev to 1.15.0

### ISSUE THREAD

**Issue by lukaszuznanski** [TYPO3-Initiatives/pwa-demo#26]
After upgrading ddev to 1.15.0 we can't properly override nginx configuration. Find a way to override global configuration.

**Comment by ogrosko** [comment]
Hello, have you find a solution for ddev 1.15? thx

**Comment by tmotyl** [comment]
@ogrosko can you check https://github.com/TYPO3-Initiatives/pwa-demo/pull/30 ?

**Comment by ogrosko** [comment]
Hi @tmotyl,
I've checked it but lines 5-7 in [`frontend.conf`](https://github.com/ogrosko/pwa-demo/blob/31976463c9152947caa74e24ca64a82aa0e96d5a/.ddev/nginx_full/frontend.conf#L5)  file causes ddev error:

```
Failed to restart pwa-demo: web container failed: log=phpstatus FAILED /var/www/html: OK mailhog: OK , err=container /ddev-pwa-demo-web unhealthy: phpstatus FAILED /var/www/html: OK mailhog: OK
```

After removing `server` config listening on 80 from `frontend.conf` ddev get started. 
Anyway on https://pwa-demo.ddev.site I'm getting only josn response from typo3 headless and not nuxt server response ...

Am I doing something wrong?

```
✗ ddev version
DDEV-Local version	v1.15.0
commit            	v1.15.0
db                	drud/ddev-dbserver-mariadb-10.2:v1.15.0
dba               	phpmyadmin/phpmyadmin:5
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.15.0
docker            	19.03.12
docker-compose    	1.27.2
os                	darwin
router            	drud/ddev-router:v1.15.0
web               	drud/ddev-webserver:v1.15.0
```

**Comment by rfay** [comment]
I do hope you'll be upgrading to v1.15.3 of course. 

Nginx configuration changed in v1.15. see [release notes](https://github.com/drud/ddev/releases/tag/v1.15.0) and [docs](https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#providing-custom-nginx-configuration)

**Comment by jan-vodila** [comment]
Hello,

I had the same issue and I fixed it by merging content of the [frontend.conf](https://github.com/ogrosko/pwa-demo/blob/31976463c9152947caa74e24ca64a82aa0e96d5a/.ddev/nginx_full/frontend.conf) file into [nginx-site.conf](https://github.com/ogrosko/pwa-demo/blob/31976463c9152947caa74e24ca64a82aa0e96d5a/.ddev/nginx_full/nginx-site.conf), so I have only file now with multiple server configs and everything works fine.

**Comment by tmotyl** [comment]
@jan-vodila can you send a PR?

**Comment by tmotyl** [comment]
@lukaszuznanski is this fixed or should be kept open?
